version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        description: "This table contains the raw listings data from Airbnb." 
      - name: hosts
        identifier: raw_hosts
        description: "This table contains the raw hosts data from Airbnb."
      - name: reviews
        identifier: raw_reviews
        description: "This table contains the raw reviews data from Airbnb."
